export { default as AdminDashboard } from './Admin/Admin';
export { default as AdminProducts } from './AdminProducts/AdminProducts';
export { default as Products } from './Products/Products';
export { default as ProductDetail } from './ProductDetail/ProductDetail';
export { default as CustomOrder } from './CustomOrder/CustomOrder';
export { default as AdminTransactions } from './AdminTransactions/AdminTransactions';
export { default as adminTransactionDetail } from './adminTransactionDetail/adminTransactionDetail';
export { default as Sale } from './SaleProducts/SaleProducts';
export { default as Home } from './Home/Home';
